### ISSUE TITLE
How to modify murax to get Muraxy

### ISSUE THREAD

**Issue by LongStudy** [robindust-ce/vexriscv_blog#1]
Hello, I want to know how to modify murax to get high-performance Muraxy, it seems that in addition to modifying IBusSimplePlugin and DBusSimplePlugin to their cache versions, also need to modify the bus link. Do you have any plans to open source the modified murax configuration? Waiting for your response and thank you a lot!

**Comment by robindust-ce** [comment]
Hey,
I just replaced the link to the VexRiscV Repository with an actual (modified) copy. [VexRiscv.copy/src/main/scala/vexriscv/demo/Muraxy.scala](https://github.com/robindust-ce/vexriscv_blog/blob/8a108931be9ccfb4101b815f8a8e624e6306ea64/VexRiscv.copy/src/main/scala/vexriscv/demo/Muraxy.scala) contains the Muraxy configuration. It has the bus architecture of the Briey SoC but the peripherals of the Murax SoC.
Hope this helps!

**Comment by LongStudy** [comment]
Thank you very much for your reply, which has answered my doubts. I will also try to modify and hope to reproduce your coremark score result.
